# Grundeinstellungen
output:
  directory: "data"
  filename: "insider_trades.csv"
  format: "csv"  # Mögliche Werte: csv, parquet

# Scraping-Einstellungen
scraping:
  start_year: 2025  # Ab welchem Jahr sollen Daten geholt werden
  start_month: 1    # Ab welchem Monat im start_year
  max_workers: 10   # Anzahl paralleler Downloads
  retry_attempts: 3 # Anzahl Wiederholungsversuche bei Fehlern
  timeout: 30       # Timeout in Sekunden für HTTP-Requests

# Filter-Einstellungen
filters:
  min_transaction_value: 0     # Minimaler Transaktionswert in USD
  transaction_types: []        # Leer = alle Typen, oder Liste: ["P", "S", "A", etc.]
  exclude_companies: []        # Liste von Ticker-Symbolen die ausgeschlossen werden sollen
  include_companies: []        # Liste von Ticker-Symbolen die ausgeschlossen werden sollen
  min_shares_traded: 0        # Minimale Anzahl gehandelter Aktien

# Logging-Einstellungen
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  file: "openinsider.log"
  rotate_logs: true          # Alte Logs archivieren
  max_log_size: 10           # Maximale Log-Größe in MB

# Cache-Einstellungen
cache:
  enabled: true              # Cache aktivieren/deaktivieren
  directory: ".cache"        # Cache-Verzeichnis
  max_age: 24               # Maximales Alter der Cache-Dateien in Stunden
